### ISSUE TITLE
Retry sample tracking update

### ISSUE THREAD

**Issue by wow-such-code** [qbicsoftware/etl-scripts#56]
In ETL scripts using sample tracking service, registration of data fails if sample tracking database has issues. If this happens, communication should be retried once or twice.

**Comment by wow-such-code** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Retry sample tracking update once or twice in all relevant ETL scripts](https://trello.com/c/IFdEEa9J/436-retry-sample-tracking-update-once-or-twice-in-all-relevant-etl-scripts)

**Comment by sven1103** [comment]
solved with #59
